src/layout/default.html
I’ve added a fix for the standard viewport meta tag. The reason behind this, is explained at [Mattias Kihlström’s blog](http://kihlstrom.com/2015/shrink-to-fit-no-fixes-zoom-problem-in-ios-9/):
> In iOS 9 Apple has changed how Safari handles the viewport zoom at page load. Before, if you added `<meta name="viewport" content="widh=device-width, initial-scale=1">` to the head of your HTML document, you knew that the page would render at the width of the device (in CSS pixels) and be zoomed at 100%. Any elements wider than the device width or absolute positioned elements outside of the normal viewport would not affect the initial zoom.
> After the release of iOS 9 this is no longer the way it works. Instead of initially hiding things that does not fit the page horizontally, the browser will …
=> added viewport zoom fix for iOS 9

config.js, gulpfile.js, tasks/browsersync.js, tasks/clean.js, tasks/css.js, tasks/githooks.js, tasks/html.js, tasks/img.js, tasks/js.js, tasks/upload.js, tasks/zip.js
It turns out the current setup of defining gulp tasks in a `tasks/` subfolder to keep it all manageable, can be achieved with a gulpfile.js that has half the code, and it's more readable. An [example can be found here](https://gist.github.com/branneman/c7c52fe54ac880f08a9f).
The principal change is moving away from `module.exports = function() {...}` and just let the subtask files call `gulp.task()` directly. This means that there's only group-tasks in the `gulpfile.js` from now on, nice and clean.
=> Refactored gulp tasks/subtasks setup

.gitignore, config.js, tasks/css.js, tasks/docs.js, tasks/docs/index.html
This will add documentation to the bootstrap (gulp task ```gulp doc```).
The ```css-sassdoc``` has been moved to ```gulp doc``` because sassdoc is documentation.
It also the requested outcome/solution for #24
=> Added Sassdoc to the documentation

src/static/scss/all.scss
I placed the import of _colors.scss above _typography.scss. This is because I encountered a simple “undefined variable” error in SASS. I think most people would like to use colors as well in their typography rules, so that’s why I switched them.
=> Changed order of common scss files

src/static/scss/vendor/_normalize.scss
I noticed there was a new release of Normalize.css, which was released this weekend. At https://github.com/necolas/normalize.css/blob/master/CHANGELOG.md#400-march-19-2016 you can find the changelog. The main reason for me to upgrade is better comments which explain more and to identify opinionated styles
=> Upgrade to Normalize.css 4.0.0

tasks/docs/layout/preview.html
Fixes a bug on the component preview page. Bootstrap was included when the component preview was rendered, causing the bootstrap css to conflict with the component's css.
=> Remove bootstrap css from component preview render

.eslintignore
All `shim` files should be stored in the `polyfill` folder
=> Unused path .eslintignore

.stylelintrc.yml, package.json
As of Stylelint 7.8.0, three of our used rules are deprecated. As of Stylelint 8.0 they will be removed. Therefore I’ve updated our dependency of stylelint-config-standard to version 16 and changed one rule of our own configuration
=> Updated (S)CSS linter Stylelint configuration

src/static/scss/util/_position.scss
Apparently, if the line 2 is empty, the sassdoc layout will break.
=> added /// on the empty line to complete the comment

config.js, package.json, src/static/scss/util/_position.scss, tasks/docs.js, tasks/docs/index.html
Resolve #50.
A deprecated warning of Swig when installing the bootstrap (which was required by a dependency of sassdoc) is also gone.
=> Remove sassdoc

package.json
For the second time, I stumbled upon [https://evilmartians.com/chronicles/autoprefixer-7-browserslist-2-released](https://evilmartians.com/chronicles/autoprefixer-7-browserslist-2-released).
The following reasons are why Autoprefixer has been updated:
- Reducing size of node_modules with around 6MB
- Several issues concerning Grid Layout
- Updated PostCSS (better performance)
- Switch to Browserslist 2
As https://github.com/postcss/autoprefixer/blob/master/CHANGELOG.md mentions “Use PostCSS 6.0” at release 7.0, I’ve updated PostCSS as well by updating gulp-postcss to version 7.0.0
Browserslist 2 brings us better support for other browsers next to the “main browsers” when it comes to using `last n versions`
=> Upgrade to Autoprefixer 7.1.1

.browserslistrc, config.js, tasks/css.js
We have a support config for Browserslist (used by Autoprefixer) that’s opinionated. I’m proposing to change it to default, unless we have a very good reason for it. Each developer should change the default setting to its own needs.
=> Moved to default support config for Autoprefixer

tasks/githooks.js
A small tweak to make sure that githooks can be executed on macOS/Linux after being copied.
Should work fine on windows machines but needs to be tested also.
=> Githooks fix

config.js, package.json, tasks/docs.js, tasks/docs/index.njk, tasks/util/docHelpers.js
As discussed during the guild meeting, template and component listings are now fully recursive.
- The [index template](73/files#diff-9e77f4d290a8e2f1e1611701e360aea2) has been greatly simplified, only taking in the generated data structures for templates and components and calling a single recursive macro for generating the tree.
- [`docHelpers.js`](73/files#diff-9530f5b2288e828561d192f282e88a65):
- A new generic directory tree walking function (`getTree`) has been introduced for generating the template and component data structures, which takes a configuration object to handle the differences between the template and component data structures.
- Globbing has been removed in favour of directory tree walking because a flat data structure isn't useful anymore when the goal is to produce a …
=> Template and component listings on the index are now fully recursive and follow the same logic

config.js, package.json, readme.md, src/components/list/list-waffles.json, src/components/list/list.json, src/components/list/list.njk, src/components/list/list.yml, src/components/nav/nav.json, src/components/nav/nav.njk, src/templates/home.json, src/templates/home.njk, tasks/docs.js, tasks/html.js, tasks/util/docHelpers.js, tasks/util/envManager.js, tasks/util/nunjucks-extensions.js
**Update 16 march**: Based on feedback during the last guild meeting, and from some folks individually, several options have been added:
* A custom 'component' Nunjucks tags that automatically loads a component's eponymous JSON file if it has one, with an optional second argument for specifying an alternate data source path or object;
* Automatic loading of JSON data from a template's eponymous JSON file, if it has one;
* Documentation was updated to describe all new options and configurations;
* A new demo component was added with various configurations to demonstrate the new functionality. 
Full details of functionality is described in the updated readme: https://github.com/colin-aarts/frontend-bootstrap/blob/bf6ea0f48ed556fde495265b35721f07719a5953/readme.md#how-to-component-library …
=> Add support for loading JSON in templates

src/static/js/main.js
This PR fixes the initial (domready) component initialization. Currently, the `then` resolve callback is passed the result of `initializeComponents(document)` (`undefined`) instead of an actual callback which executes that function.
This causes component initialization to proceed immediately, regardless of actual domready status. Elements with modules attached that aren't ready yet will simply never be initialized.
=> Fix initial component initialization

.travis.yml, readme.md
In this PR I've added TravisCI configuration. I've chosen to run tests on linux & macOS against the Node.js LTS, but not the current Node.js Stable because it breaks. The tasks ran are `npm run dist` and `npm run test`, preceded by `npm i`.
I've also added a readme badge which points to the build/test results page at Travis:
https://travis-ci.org/mirabeau-nl/frontend-boilerplate
=> Added TravisCI configuration and badge

tasks/js.js
The previous PR had an issue where the js-browserify would fail silently instead of finishing.
=> Fixed a regression bug where the js-browserify task would fail silently

config.js, package.json, readme.md
I added an optional `--https` flag to start browsersync in https mode.
Example:
`yarn dev` - starts dev environment in http mode
`yarn dev --https` - starts dev environment in https mode
=> feature/browsersync-config: Added handling optional "--https" argument to start browsersync in https mode

package-lock.json, package.json, tasks/codestyle.js
Last update for `ignore` npm package appeared to cause eslint issues, which we noticed on `abccd-website` project. After rolling the package back, the issue was fixed, therefore we should for now do the same on this starting point repository.
=> fix/ignore-package: fix: roll-back ignore package to stable version

gulpfile.babel.js, tasks/html.js
Isolate code style changes that get done by pre-commit githook on several lines, to bring codebase in line with prettier formatting rules, so these changes wouldn't smuggle themselves with other code changes
=> Format code in accordance with prettier formatting rules

README.md
Add badges to let us keep an eye on outdated dependencies, test coverage and dependency vulnerabilities.
=> Add quality badges to README

config.js, package-lock.json, package.json, tasks/docs.js, tasks/docs/index.njk
I’m removing the dependency Moment.js and Moment-Timezone, because we don’t need it. We can use the Intl.DateTimeFormat object for quite a while now in Node.js. This change will save some disk space.
For delivery purposes, we show when the library has last been updated. This can be particularly useful for projects where we work with clients or colleagues that are in a different time zone. For extra clarity, the format will change from a mixed English/Dutch locale to British. `Last updated: 10-12-2020 13:37:00 CET` will become `Last updated: 10 December 2020 13:37:00 CET` with my change.
Configuration is available for people who need to set the correct time zone they’re working form, or when they want to change the format.
=> Remove Moment.js in favour of plain JS

.stylelintrc.yml
Whitelist has been deprecated, allowed-list should be used instead. With this change we have a warning less on the command line while executing linting.
=> chore(stylelint): use allowed-list instead of deprecated whitelist

README.md
I noticed the links in the table of contents didn’t work on Github. I’ve changed them and fixed two spelling mistakes.
=> docs: fix links and spelling

config.js
In PR #133 I’ve added redundant configuration for the date style. This was to provide a fallback to Node < 13. As of Node 15 this method of providing redundant config is not permitted anymore.
In this PR I’m removing the fallback in favour of clean code; making the Boilerplate more future proof.
=> fix(docs): support for Node v15+

.travis.yml
Travis build were failing due to a bug in npm 6. By using the latest node version instead of the LTS one the checks pass again! 👍
=> feature(travis): Upgrade travis to latest version to fix npm ci issues
